# Doc: http://www.appveyor.com/docs/appveyor-yml
# See https://github.com/gruntjs/grunt/blob/master/appveyor.yml
# for a good example for node projects.

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"

matrix:
  allow_failures:
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - ps: "npm test # PowerShell"
  - cmd: npm test

build: off

version: "{build}"
